name: Deploy to main/docs

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-docs
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # Usa a versão do pnpm definida em package.json (packageManager)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (Pages mode)
        run: pnpm run build:pages

      - name: SPA fallback (copy index.html to 404.html)
        run: cp dist/index.html dist/404.html
      
        
      # - name: Deploy to main/docs
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: main
      #     folder: dist
      #     target-folder: docs
      #     clean: true
      #     single-commit: true
      #     commit-message: 'chore(pages): deploy dist to docs [skip ci]'
      - name: Ensure .ssh directory exists
        run: mkdir -p ~/.ssh
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
    
      - name: Add server to known_hosts
        run: ssh-keyscan 145.223.95.9 >> ~/.ssh/known_hosts
      
      - name: Coopy path
        run: rsync -avz --delete ./ root@145.223.95.9:/home/fabio/projetos/a0
      
      - name: Deplou to Server
        run: |
          ssh root@145.223.95.9 << EOF
            $DEPLOY_COMMAND
          EOF
           
